# Generated by Django 3.0.1 on 2019-12-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20191224_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('cal', models.TextField()),
            ],
        ),
    ]
